package icons;

import javax.swing.Icon;

import com.intellij.openapi.util.IconLoader;

/**
 * NOTE THIS FILE IS AUTO-GENERATED by the build/scripts/icons.gant
 * Don't repeat mistakes of others ;-)
 */
public class CFMLIcons {
  private static Icon load(String path) {
    return IconLoader.getIcon(path, CFMLIcons.class);
  }

  public static final Icon Cfml = load("/icons/cfml.png"); // 16x16
  public static final Icon Cfunit = load("/icons/cfunit.png"); // 16x16
  public static final Icon Remote_access = load("/icons/remote_access.png"); // 16x16
}
